const AppRoute = {
    homepage: "/",
    signup: "/signup",
    signin: "/signin",
    signout: "/signout",
    reset: "/reset",
    tour: "/tour",
    ourteam: "/ourteam",
    donate: "/donate",
    trainings: "/trainings",
    zoom: "/zoom",
    club: "/club",
    about: "/about_us",
    merch: "/merch",
    people: "/people",
    events: "/events",
    plans: "/plans",
    products: "/products",
    detail: "/detail",
    testimonials: "/testimonials",
    instructor: "/instructor",
    contact: "/contact",
    forgotPassword: "/forgotpassword",
    privacy: "/privacy",
    terms: "/terms",
    team: "/team",
    choreography: "/choreography",
    profile: "/dashboard",
    profileVideos: "/profile/videos",
    profileProductOrders: "/profile/product_orders",
    profilePlanOrders: "/profile/orders",
    profileEventTickets: "/profile/reviews",
    profileEventTickets: "/profile/event_tickets",
    profileReviews: "/profile/reviews",
    profileMerchandise: "/profile/merchandise"
}

export default AppRoute;